export const jobTitle = 'Manager';
export const fallbackJobTitle = 'Designer';
export const uniqueEmail = `test_${Date.now()}@mail.com`;
export const jobCategory = 'IT & Digital Solutions';
export const location = 'London, England';
export const confirmMessage = 'Your subscription was submitted successfully.';
export const messageWithoutSavedJobs = 'No jobs have been saved yet.';
export const jobsPageURL = '/global/en/jobs/';
export const ikeaJobsPageURL = 'https://jobs.ikea.com/en';